[package]
name = "slack-auth-middleware"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
chrono = "0.4.38"
futures-util = "0.3.30"
hex = "0.4.3"
hmac = "0.12.1"
http-body-util = "0.1.2"
sha2 = "0.10.8"
tower = "0.5.1"
